# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  generic-crd-plugin:
    image: ghcr.io/loft-sh/vcluster-generic-crd-plugin
    imagePullPolicy: IfNotPresent
    rbac:
      role:
        extraRules:
          # Example:
          # - apiGroups: ["cert-manager.io"]
          #   resources: ["issuers", "certificates", "certificaterequests"]
          #   verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
    env:
      - name: CONFIG
        value: |-
          version: v1beta1
          mappings: []
