# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  generic-crd-plugin:
    image: ghcr.io/loft-sh/vcluster-generic-crd-plugin
    imagePullPolicy: IfNotPresent
    rbac:
      role:
        extraRules:
          - apiGroups: ["monitoring.coreos.com"]
            resources: ["servicemonitors"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
    env:
      - name: CONFIG
        value: |-
          version: v1beta1
          mappings:
            - fromVirtualCluster:
                apiVersion: monitoring.coreos.com/v1
                kind: ServiceMonitor
                patches:
                  - op: add
                    path: .metadata.labels
                    #
                    # User TODO:
                    # Set the value below according to the .spec.serviceMonitorSelector of your Prometheus
                    value:
                      release: prometheus
                  - op: rewriteLabelKey
                    path: .spec.jobLabel
                  - op: rewriteLabelKey
                    path: .spec.targetLabels[*]
                  - op: rewriteLabelKey
                    path: .spec.podTargetLabels[*]
                  - op: rewriteName
                    path: .spec.endpoints[*]
                  - op: rewriteLabelExpressionsSelector
                    path: .spec.selector
                    # TODO: Dev: add transformed namespace selectors to the label selectors (.spec.selector)
                    # FR - https://github.com/loft-sh/vcluster-generic-crd-sync-plugin/issues/15
                  - op: replace
                    path: .spec.namespaceSelector
                    value:
                      any: false
                      matchNames: []
