# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  contour:
    image: ghcr.io/loft-sh/vcluster-generic-crd-plugin
    imagePullPolicy: IfNotPresent
    rbac:
      role:
        extraRules:
          - apiGroups: ["projectcontour.io"]
            resources: ["httpproxies", "extensionservices"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
    env:
      - name: CONFIG
        value: |-
          version: v1beta1
          mappings:
            - fromVirtualCluster:
                # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
                apiVersion: projectcontour.io/v1
                kind: HTTPProxy
                patches:
                  - op: rewriteName
                    path: spec.routes..services..name
                  - op: rewriteName
                    path: spec.virtualhost.tls.secretName
                    sync:
                      secret: true
                  - op: rewriteName
                    path: spec.tcpproxy.services..name
                  - op: rewriteName
                    path: spec.includes
                    namePath: name
                    namespacePath: namespace
                reversePatches:
                  - op: copyFromObject
                    fromPath: status
                    path: status